# 分类算法案例：预测饭店销量

## 导入数据

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier

inputfile = 'data/sales_data.xls'
data = pd.read_excel(inputfile, index_col=u'序号')  # 导入数据
data

天气 是否周末 是否有促销 销量
序号                 
1   坏    是     是  高
2   坏    是     是  高
3   坏    是     是  高
4   坏    否     是  高
5   坏    是     是  高
6   坏    否     是  高
7   坏    是     否  高
8   好    是     是  高
9   好    是     否  高
10  好    是     是  高
11  好    是     是  高
12  好    是     是  高
13  好    是     是  高
14  坏    是     是  低
15  好    否     是  高
16  好    否     是  高
17  好    否     是  高
18  好    否     是  高
19  好    否     否  高
20  坏    否     否  低
21  坏    否     是  低
22  坏    否     是  低
23  坏    否     是  低
24  坏    否     否  低
25  坏    是     否  低
26  好    否     是  低
27  好    否     是  低
28  坏    否     否  低
29  坏    否     否  低
30  好    否     否  低
31  坏    是     否  低
32  好    否     是  低
33  好    否     否  低
34  好    否     否  低

In [2]:
# 数据是类别标签，要将它转换为数据
# 用1来表示“好”、“是”、“高”这三个属性，用-1来表示“坏”、“否”、“低”
data[data == u'好'] = 1
data[data == u'是'] = 1
data[data == u'高'] = 1
data[data != 1] = -1
x = data.iloc[:, :3].as_matrix().astype(int)
print(x)
y = data.iloc[:, 3].as_matrix().astype(int)
print(y)

[[-1  1  1]
 [-1  1  1]
 [-1  1  1]
 [-1 -1  1]
 [-1  1  1]
 [-1 -1  1]
 [-1  1 -1]
 [ 1  1  1]
 [ 1  1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1 -1  1]
 [ 1 -1  1]
 [ 1 -1  1]
 [ 1 -1 -1]
 [-1 -1 -1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 1 -1  1]
 [-1 -1 -1]
 [-1 -1 -1]
 [ 1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 1 -1 -1]
 [ 1 -1 -1]]
[ 1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1]


## 拆分训练数据与测试数据

In [3]:
# 拆分训练数据与测试数据
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# 训练KNN分类器

In [4]:
clf = KNeighborsClassifier(algorithm='kd_tree')
clf.fit(x_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

## 测试结果

In [5]:
# 测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean(answer == y_test))

[[ 1 -1  1]
 [-1  1  1]
 [-1 -1  1]
 [ 1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 1  1  1]]
[-1  1 -1 -1 -1 -1  1]
[ 1  1  1  1 -1  1  1]
0.428571428571


## 准确率

In [6]:
# 准确率
precision, recall, thresholds = precision_recall_curve(y_train, clf.predict(x_train))
print(classification_report(y_test, answer, target_names=['高', '低']))

             precision    recall  f1-score   support

          高       0.20      1.00      0.33         1
          低       1.00      0.33      0.50         6

avg / total       0.89      0.43      0.48         7



# 训练贝叶斯分类器

In [7]:
# 训练贝叶斯分类器
clf = BernoulliNB()
clf.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

## 测试结果

In [8]:
# 测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean(answer == y_test))

[[ 1 -1  1]
 [-1  1  1]
 [-1 -1  1]
 [ 1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 1  1  1]]
[-1  1 -1 -1 -1 -1  1]
[ 1  1  1  1 -1  1  1]
0.428571428571


## 准确率

In [9]:
print(classification_report(y_test, answer, target_names=['低', '高']))

             precision    recall  f1-score   support

          低       0.20      1.00      0.33         1
          高       1.00      0.33      0.50         6

avg / total       0.89      0.43      0.48         7



# 决策树

In [10]:
from sklearn.tree import DecisionTreeClassifier as DTC

dtc = DTC(criterion='entropy')  # 建立决策树模型，基于信息熵
dtc.fit(x_train, y_train)  # 训练模型

# 导入相关函数，可视化决策树。
# 导出的结果是一个dot文件，需要安装Graphviz才能将它转换为pdf或png等格式。

# https://graphviz.gitlab.io/_pages/Download/Download_windows.html
# 安装Graphviz https://graphviz.gitlab.io/_pages/Download/windows/graphviz-2.38.msi

from sklearn.tree import export_graphviz

with open("data/tree.dot", 'w') as f:
    f = export_graphviz(dtc, out_file=f)

## 测试结果

In [11]:
# 测试结果
answer = dtc.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean(answer == y_test))

[[ 1 -1  1]
 [-1  1  1]
 [-1 -1  1]
 [ 1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 1  1  1]]
[-1  1 -1 -1 -1 -1  1]
[ 1  1  1  1 -1  1  1]
0.428571428571


## 准确率

In [12]:
print(classification_report(y_test, answer, target_names=['低', '高']))

             precision    recall  f1-score   support

          低       0.20      1.00      0.33         1
          高       1.00      0.33      0.50         6

avg / total       0.89      0.43      0.48         7



# SVM

In [13]:
from sklearn.svm import SVC

clf = SVC()
clf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## 测试结果

In [14]:
# 测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean(answer == y_test))

[[ 1 -1  1]
 [-1  1  1]
 [-1 -1  1]
 [ 1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 1  1  1]]
[-1  1 -1 -1  1 -1  1]
[ 1  1  1  1 -1  1  1]
0.285714285714


## 准确率

In [15]:
print(classification_report(y_test, answer, target_names=['低', '高']))

             precision    recall  f1-score   support

          低       0.00      0.00      0.00         1
          高       0.67      0.33      0.44         6

avg / total       0.57      0.29      0.38         7



参考资料：炼数成金Python数据分析课程