# pandas

## Series


In [1]:
import numpy as np
import pandas as pd
import sys
from pandas import Series, DataFrame


obj = Series([4, 7, -5, 3])
print(obj)
print(obj.values)
print(obj.index)

0    4
1    7
2   -5
3    3
dtype: int64
[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [2]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
print(obj2.index)
print(obj2['a'])

d    4
b    7
a   -5
c    3
dtype: int64
Index(['d', 'b', 'a', 'c'], dtype='object')
-5


In [3]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [4]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [5]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [6]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [7]:
'b' in obj2

True

In [8]:
'e' in obj2

False

In [9]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
print(obj3)

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64


In [10]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
print(obj4)

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [11]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [12]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [13]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [14]:
print(obj3)
print(obj4)
print(obj3 + obj4)

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [15]:
obj4.name = 'population'
obj4.index.name = 'state'
print(obj4)

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [16]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj)

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


## dataframe

In [17]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

print(frame)

   pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002


In [18]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [19]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
print(frame2)
print(frame2.columns)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [21]:
print(frame2['state'])
print(frame2.year)
print(frame2.loc['three'])

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object
one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64
year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


In [22]:
frame2['debt'] = 16.5
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5


In [23]:
frame2['debt'] = np.arange(5.)
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0


In [24]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7


In [25]:
frame2['eastern'] = frame2.state == 'Ohio'
print(frame2)

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False


In [26]:
del frame2['eastern']
print(frame2.columns)

Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [27]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
print(frame3)
print(frame3.T)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6


In [28]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [29]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [30]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
print(frame3)
print(frame3.values)

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6
[[ nan  1.5]
 [ 2.4  1.7]
 [ 2.9  3.6]]


## 索引对象

In [31]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
print(index)
print(index[1:])

# index[1] = 'd'
# TypeError: Index does not support mutable operations

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')


In [32]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [33]:
print(frame3)
print('Ohio' in frame3.columns)
print(2003 in frame3.index)

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6
True
False


## 数据读取

### 读取文本格式数据 pd.read_csv

In [34]:
# 读取文本格式数据
path = 'data/'
df = pd.read_csv(path + '/ex1.csv')
print(df)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


### OSError: Initializing from file failed 处理方法

出现这个问题大部分原因是文件路径中包含中文，解决办法有两个

1.参数中添加 engine='python' 

data = pd.read_csv("E:\Python数据分析\data\ex1.csv",engine='python')

2.通过 open 读取

data = pd.read_csv(open("E:\Python数据分析\data\ex1.csv"))


In [35]:
pd.read_table(path + '/ex1.csv', sep=',')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [36]:
pd.read_csv(path + '/ex2.csv', header=None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [37]:
pd.read_csv(path + '/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [38]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv(path + '/ex2.csv', names=names, index_col='message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [39]:
parsed = pd.read_csv(path + '/csv_mindex.csv', index_col=['key1', 'key2'])
print(parsed)

           value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16


In [40]:
list(open(path + '/ex3.txt'))
result = pd.read_table(path + '/ex3.txt', sep='\s+')
print(result)

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491


In [41]:
pd.read_csv(path + '/ex4.csv', skiprows=[0, 2, 3])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [42]:
result = pd.read_csv(path + '/ex5.csv')
print(result)
print(pd.isnull(result))

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo
   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False


In [43]:
result = pd.read_csv(path + '/ex5.csv', na_values=['NULL'])
print(result)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo


In [44]:
# 把符合条件的数据赋值为NaN
result = pd.read_csv(path + '/ex5.csv', na_values=['NULL'])
print(result)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo


In [45]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv(path + '/ex5.csv', na_values=sentinels)

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [46]:
# 逐行读取文本文件
result = pd.read_csv(path + '/ex6.csv')
print(result)
pd.read_csv(path + '/ex6.csv', nrows=5)

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
5     1.817480  0.742273  0.419395 -2.251035   Q
6    -0.776764  0.935518 -0.332872 -1.875641   U
7    -0.913135  1.530624 -0.572657  0.477252   K
8     0.358480 -0.497572 -0.367016  0.507702   S
9    -1.740877 -1.160417 -1.637830  2.172201   G
10    0.240564 -0.328249  1.252155  1.072796   8
11    0.764018  1.165476 -0.639544  1.495258   R
12    0.571035 -0.310537  0.582437 -0.298765   1
13    2.317658  0.430710 -1.334216  0.199679   P
14    1.547771 -1.119753 -2.277634  0.329586   J
15   -1.310608  0.401719 -1.000987  1.156708   E
16   -0.088496  0.634712  0.153324  0.415335   B
17   -0.018663 -0.247487 -1.446522  0.750938   A
18   -0.070127 -1.579097  0.120892  0.671432   F
19   -0.194678 -0.49

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [47]:
chunker = pd.read_csv(path + '/ex6.csv', chunksize=1000)
tot = Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
print(tot[:10])

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64


## 文件写出 to_csv

In [48]:
# 文件写出
data = pd.read_csv(path + '/ex5.csv')
print(data)
data.to_csv(path + '/out.csv')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo


In [49]:
data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo


In [50]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo


In [51]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo


In [52]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0


In [53]:
dates = pd.date_range('1/1/2000', periods=7)
ts = Series(np.arange(7), index=dates)
ts.to_csv('data/tseries.csv')

Series.from_csv('data/tseries.csv', parse_dates=True)

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
dtype: int64

手工处理分隔符格式 csv

In [54]:
# 手工处理分隔符格式
import csv

f = open(path + '/ex7.csv')

reader = csv.reader(f)

for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3', '4']


In [55]:
lines = list(csv.reader(open(path + '/ex7.csv')))
header, values = lines[0], lines[1:]
data_dict = {h: v for h, v in zip(header, zip(*values))}
print(data_dict)

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}


In [56]:
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL


with open(path + 'mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))
pd.read_table(path + 'mydata.csv', sep=';')

one  two  three
0    1    2      3
1    4    5      6
2    7    8      9

# Excel数据

## 生成xls工作薄

In [62]:
# Excel数据
# 生成xls工作薄
import xlrd, xlwt

path = 'data/'

wb = xlwt.Workbook()
print(wb)

wb.add_sheet('first_sheet', cell_overwrite_ok=True)
wb.get_active_sheet()

ws_1 = wb.get_sheet(0)
print(ws_1)

ws_2 = wb.add_sheet('second_sheet')

data = np.arange(1, 65).reshape((8, 8))
print(data)

ws_1.write(0, 0, 100)

for c in range(data.shape[0]):
    for r in range(data.shape[1]):
        ws_1.write(r, c, int(data[c, r]))
        ws_2.write(r, c, int(data[r, c]))

wb.save(path + 'workbook.xls')


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [ ]:
# 从工作薄中读取
book = xlrd.open_workbook(path + 'workbook.xls')
book.sheet_names()

sheet_1 = book.sheet_by_name('first_sheet')
sheet_2 = book.sheet_by_index(1)
print(sheet_1)
print(sheet_2.name)

print(sheet_1.ncols)
print(sheet_1.nrows)

cl = sheet_1.cell(0, 0)
print(cl.value)
print(cl.ctype)

print(sheet_2.row(3))
print(sheet_2.col(3))

print(sheet_1.col_values(3, start_rowx=3, end_rowx=7))
print(sheet_1.row_values(3, start_colx=3, end_colx=7))

for c in range(sheet_1.ncols):
    for r in range(sheet_1.nrows):
        print('%s' % sheet_1.cell(r, c).value)

## 生成xlsx工作薄

### 从工作薄中读取

### 使用pandas读取

In [63]:
# 使用pandas读取
xls_file = pd.ExcelFile(path + 'workbook.xls')
table = xls_file.parse('first_sheet')

# JSON数据

In [64]:
# JSON数据
import json

obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"},
              {"name": "Katie", "age": 33, "pet": "Cisco"}]
}
"""

result = json.loads(obj)
print(result)

asjson = json.dumps(result)

siblings = DataFrame(result['siblings'], columns=['name', 'age'])
print(siblings)

{'name': 'Wes', 'places_lived': ['United States', 'Spain', 'Germany'], 'pet': None, 'siblings': [{'name': 'Scott', 'age': 25, 'pet': 'Zuko'}, {'name': 'Katie', 'age': 33, 'pet': 'Cisco'}]}
    name  age
0  Scott   25
1  Katie   33


# 二进制数据格式

In [65]:
# 二进制数据格式
# pickle
frame = pd.read_csv(path + '/ex1.csv')
print(frame)
frame.to_pickle(path + '/frame_pickle')

pd.read_pickle(path + '/frame_pickle')


   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

# HDF5格式

In [66]:
# HDF5格式
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
print(store)

print(store['obj1'])

store.close()

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5
/obj1                frame        (shape->[3,5])
/obj1_col            series       (shape->[3])  
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


In [67]:
import os

os.remove('mydata.h5')

# 使用HTML和Web API

In [68]:
# 使用HTML和Web API
import requests

url = 'https://api.github.com/repos/pydata/pandas/milestones/28/labels'
resp = requests.get(url)
print(resp)

data = json.loads(resp.text)

issue_labels = DataFrame(data)
print(issue_labels)

<Response [200]>
     color  default        id             name                   node_id  \
0   e10c02    False     76811              Bug      MDU6TGFiZWw3NjgxMQ==   
1   4E9A06    False     76812      Enhancement      MDU6TGFiZWw3NjgxMg==   
2   FCE94F    False    127681         Refactor      MDU6TGFiZWwxMjc2ODE=   
3   75507B    False    129350            Build      MDU6TGFiZWwxMjkzNTA=   
4   3465A4    False    134699             Docs      MDU6TGFiZWwxMzQ2OTk=   
5   AFEEEE    False    211840       Timeseries      MDU6TGFiZWwyMTE4NDA=   
6   729FCF    False    233160          Groupby      MDU6TGFiZWwyMzMxNjA=   
7   06909A    False   2301354          Data IO      MDU6TGFiZWwyMzAxMzU0   
8   8AE234    False   2413328    Visualization      MDU6TGFiZWwyNDEzMzI4   
9   0b02e1    False   2822098         Indexing      MDU6TGFiZWwyODIyMDk4   
10  d7e102    False   2822342     Missing-data      MDU6TGFiZWwyODIyMzQy   
11  a10c02    False   8935311      Performance      MDU6TGFiZWw4OTM1MzE

# 使用数据库

In [69]:
# 使用数据库
import sqlite3

query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""

con = sqlite3.connect(':memory:')
con.execute(query)
con.commit()

In [70]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

con.executemany(stmt, data)
con.commit()

In [71]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
print(rows)

[('Atlanta', 'Georgia', 1.25, 6), ('Tallahassee', 'Florida', 2.6, 3), ('Sacramento', 'California', 1.7, 5)]


In [72]:
print(cursor.description)

(('a', None, None, None, None, None, None), ('b', None, None, None, None, None, None), ('c', None, None, None, None, None, None), ('d', None, None, None, None, None, None))


In [73]:
DataFrame(rows, columns=list(zip(*cursor.description))[0])

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [74]:
import pandas.io.sql as sql

sql.read_sql('select * from test', con)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

参考资料：炼数成金Python数据分析课程